FROM python:3.12

WORKDIR /bot

COPY ./requirements.txt /bot
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the source and test directories
COPY ./src /bot/src/
COPY ./tests /bot/tests/

ENV PYTHONPATH=/bot/src

CMD ["python", "-m", "unittest", "discover", "-s", "tests"]
