FROM python:3.11

WORKDIR /bot

COPY ./requirements.txt /bot
RUN pip3 install --no-cache-dir -r requirements.txt

RUN apt-get -y update
RUN apt-get -y upgrade

# Copy the source and test directories
COPY ./src /bot/src/
COPY ./tests /bot/tests/

ENV PYTHONPATH=/bot

CMD ["python", "-m", "unittest", "tests/test_chatgpt.py"]
